import { db, jobsTable } from "@workspace/db";

const today = new Date();
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r.toISOString().split("T")[0];
};

const jobs = [
  {
    title: "Combined Graduate Level Examination (CGL) 2024",
    department: "Staff Selection Commission",
    category: "ssc",
    states: ["All India"],
    ageMin: 18,
    ageMax: 32,
    ageRelaxation: "OBC: 3 years, SC/ST: 5 years, PwD: 10 years",
    qualification: "Bachelor's Degree from any recognized University",
    applicationStartDate: addDays(today, -30),
    lastDate: addDays(today, 2),
    examDate: addDays(today, 60),
    applyUrl: "https://ssc.gov.in",
    notificationPdfUrl: "https://ssc.gov.in/SSCFileServer/PortalManagement/UploadedFiles/CGL_2024_notice.pdf",
    sourceName: "SSC Official",
    sourceUrl: "https://ssc.gov.in",
    isVerified: true,
    description: "SSC CGL 2024 recruitment for Group B and Group C posts in various Central Government Ministries, Departments and Organisations.",
    salaryRange: "₹25,500 - ₹1,51,100 per month",
    vacancies: 17727,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG format, White/Light background, 3.5 x 4.5 cm",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPEG format, Black ink on white paper",
  },
  {
    title: "Civil Services Examination 2024",
    department: "Union Public Service Commission",
    category: "upsc",
    states: ["All India"],
    ageMin: 21,
    ageMax: 32,
    ageRelaxation: "OBC: 3 years, SC/ST: 5 years, PwD (General): 10 years",
    qualification: "Bachelor's Degree (any discipline) from a recognized University",
    applicationStartDate: addDays(today, -45),
    lastDate: addDays(today, 5),
    examDate: addDays(today, 90),
    applyUrl: "https://upsconline.nic.in",
    notificationPdfUrl: "https://upsc.gov.in/sites/default/files/Notif-CSP-2024-Engl.pdf",
    sourceName: "UPSC Official",
    sourceUrl: "https://upsc.gov.in",
    isVerified: true,
    description: "UPSC Civil Services 2024 for IAS, IPS, IFS, IRS and other Central Services. Preliminary examination followed by Mains and Interview.",
    salaryRange: "₹56,100 - ₹2,50,000 per month (Pay Level 10-18)",
    vacancies: 1056,
    photoRequirements: "[STANDARD] Photo: 20-300 KB, JPEG/JPG, White background, Recent passport size",
    signatureRequirements: "[STANDARD] Signature: 10-40 KB, JPEG/JPG, Black or Blue ink",
  },
  {
    title: "IBPS PO (Probationary Officer) XIV Recruitment 2024",
    department: "Institute of Banking Personnel Selection",
    category: "banking",
    states: ["All India"],
    ageMin: 20,
    ageMax: 30,
    ageRelaxation: "SC/ST: 5 years, OBC: 3 years, PwD: 10 years",
    qualification: "Graduation in any discipline from a University recognised by the Govt. of India",
    applicationStartDate: addDays(today, -20),
    lastDate: addDays(today, 10),
    examDate: addDays(today, 45),
    applyUrl: "https://ibps.in",
    notificationPdfUrl: "https://ibps.in/wp-content/uploads/IBPS_PO_XIV_2024.pdf",
    sourceName: "IBPS Official",
    sourceUrl: "https://ibps.in",
    isVerified: true,
    description: "IBPS PO 2024 recruitment for Probationary Officers/Management Trainees in participating Public Sector Banks. CRP PO/MT-XIV.",
    salaryRange: "₹36,000 - ₹63,840 per month",
    vacancies: 4455,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG, White background, 4.5 x 3.5 cm",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPEG, Black ink on white background",
  },
  {
    title: "Railway Recruitment Board NTPC Graduate Posts 2024",
    department: "Railway Recruitment Board",
    category: "railways",
    states: ["All India"],
    ageMin: 18,
    ageMax: 33,
    ageRelaxation: "SC/ST: 5 years, OBC: 3 years, PwBD: 10 years (General)",
    qualification: "Bachelor's Degree in any discipline from a recognized University",
    applicationStartDate: addDays(today, -15),
    lastDate: addDays(today, 15),
    examDate: addDays(today, 75),
    applyUrl: "https://indianrailways.gov.in",
    notificationPdfUrl: null,
    sourceName: "RRB Official",
    sourceUrl: "https://indianrailways.gov.in",
    isVerified: true,
    description: "RRB NTPC 2024 Graduate Level Posts recruitment for Junior Clerk cum Typist, Accounts Clerk cum Typist, Station Master, Goods Guard and more.",
    salaryRange: "₹19,900 - ₹35,400 per month",
    vacancies: 11558,
    photoRequirements: null,
    signatureRequirements: null,
  },
  {
    title: "Indian Army Agniveer Recruitment Rally 2024",
    department: "Indian Army",
    category: "defence",
    states: ["Uttar Pradesh", "Bihar", "Jharkhand", "West Bengal"],
    ageMin: 17,
    ageMax: 21,
    ageRelaxation: "As per Agnipath scheme guidelines",
    qualification: "10th/12th Pass (varies by post)",
    applicationStartDate: addDays(today, -10),
    lastDate: addDays(today, 20),
    examDate: addDays(today, 50),
    applyUrl: "https://joinindianarmy.nic.in",
    notificationPdfUrl: "https://joinindianarmy.nic.in/content/dam/joinindianarmy/Agnipath-Notification-2024.pdf",
    sourceName: "Indian Army Official",
    sourceUrl: "https://joinindianarmy.nic.in",
    isVerified: true,
    description: "Agnipath Scheme - Army Recruitment Rally for Agniveer (General Duty, Clerk, Technical, Tradesmen). 4-year service period with Seva Nidhi package.",
    salaryRange: "₹30,000 - ₹40,000 per month + Seva Nidhi",
    vacancies: 25000,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG, Passport size, White background",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPEG",
  },
  {
    title: "UPPSC Combined State Engineering Service Exam 2024",
    department: "Uttar Pradesh Public Service Commission",
    category: "state-psc",
    states: ["Uttar Pradesh"],
    ageMin: 21,
    ageMax: 40,
    ageRelaxation: "As per UP government norms",
    qualification: "B.E./B.Tech in relevant engineering discipline",
    applicationStartDate: addDays(today, -25),
    lastDate: addDays(today, 8),
    examDate: addDays(today, 70),
    applyUrl: "https://uppsc.up.nic.in",
    notificationPdfUrl: "https://uppsc.up.nic.in/Attachments/AE_2024_notification.pdf",
    sourceName: "UPPSC Official",
    sourceUrl: "https://uppsc.up.nic.in",
    isVerified: true,
    description: "UPPSC AE 2024 for Assistant Engineer posts in Public Works Department, Irrigation Department and other UP Government departments.",
    salaryRange: "₹47,600 - ₹1,51,100 per month",
    vacancies: 604,
    photoRequirements: null,
    signatureRequirements: null,
  },
  {
    title: "Rajasthan Police Constable Bharti 2024",
    department: "Rajasthan Police",
    category: "police",
    states: ["Rajasthan"],
    ageMin: 18,
    ageMax: 26,
    ageRelaxation: "SC/ST Rajasthan: 5 years, OBC Rajasthan: 3 years",
    qualification: "12th Pass from a recognized board",
    applicationStartDate: addDays(today, -5),
    lastDate: addDays(today, 25),
    examDate: addDays(today, 80),
    applyUrl: "https://police.rajasthan.gov.in",
    notificationPdfUrl: null,
    sourceName: "Rajasthan Police",
    sourceUrl: "https://police.rajasthan.gov.in",
    isVerified: true,
    description: "Rajasthan Police Constable (General) and Constable (Driver) recruitment 2024. Physical and written tests included.",
    salaryRange: "₹14,600 - ₹23,100 per month + allowances",
    vacancies: 3578,
    photoRequirements: null,
    signatureRequirements: null,
  },
  {
    title: "Delhi Subordinate Services Selection Board (DSSSB) TGT/PGT Teachers",
    department: "DSSSB / Delhi Education Department",
    category: "teaching",
    states: ["Delhi"],
    ageMin: 21,
    ageMax: 32,
    ageRelaxation: "As per Delhi government rules",
    qualification: "B.Ed / M.Ed with relevant subject expertise. CTET/DTET qualified",
    applicationStartDate: addDays(today, -12),
    lastDate: addDays(today, 18),
    examDate: addDays(today, 65),
    applyUrl: "https://dsssb.delhi.gov.in",
    notificationPdfUrl: "https://dsssb.delhi.gov.in/sites/default/files/TGT_PGT_2024.pdf",
    sourceName: "DSSSB Official",
    sourceUrl: "https://dsssb.delhi.gov.in",
    isVerified: true,
    description: "DSSSB Recruitment 2024 for TGT (Trained Graduate Teacher) and PGT (Post Graduate Teacher) posts in Delhi Government Schools.",
    salaryRange: "₹47,600 - ₹1,42,400 per month",
    vacancies: 1024,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPG/JPEG, Recent passport size, White background",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPG/JPEG, Black or Blue ink on white paper",
  },
  {
    title: "BHEL Engineer Trainee 2024",
    department: "Bharat Heavy Electricals Limited",
    category: "engineering",
    states: ["All India"],
    ageMin: 18,
    ageMax: 28,
    ageRelaxation: "SC/ST: 5 years, OBC: 3 years",
    qualification: "B.E./B.Tech in Mechanical/Electrical/Electronics/Civil Engineering with 65% marks",
    applicationStartDate: addDays(today, -8),
    lastDate: addDays(today, 22),
    examDate: addDays(today, 55),
    applyUrl: "https://careers.bhel.in",
    notificationPdfUrl: null,
    sourceName: "BHEL Careers",
    sourceUrl: "https://careers.bhel.in",
    isVerified: true,
    description: "BHEL Engineer Trainee recruitment through GATE 2024 scores. Posting in various BHEL units across India.",
    salaryRange: "₹60,000 - ₹1,80,000 per month (CTC)",
    vacancies: 150,
    photoRequirements: null,
    signatureRequirements: null,
  },
  {
    title: "AIIMS Delhi Staff Nurse Grade-II 2024",
    department: "All India Institute of Medical Sciences, New Delhi",
    category: "medical",
    states: ["Delhi"],
    ageMin: 18,
    ageMax: 30,
    ageRelaxation: "OBC: 3 years, SC/ST: 5 years",
    qualification: "B.Sc Nursing (4 years) from recognized institution + Registered with Indian Nursing Council",
    applicationStartDate: addDays(today, -18),
    lastDate: addDays(today, 12),
    examDate: addDays(today, 50),
    applyUrl: "https://aiimsexams.ac.in",
    notificationPdfUrl: "https://aiimsexams.ac.in/Notifications/StaffNurse2024.pdf",
    sourceName: "AIIMS Exams",
    sourceUrl: "https://aiimsexams.ac.in",
    isVerified: true,
    description: "AIIMS Delhi Staff Nurse Grade-II Direct Recruitment 2024. Online test followed by merit list. Posting at AIIMS New Delhi.",
    salaryRange: "₹44,900 - ₹1,42,400 per month (Level 7)",
    vacancies: 256,
    photoRequirements: "[STANDARD] Photo: 40-100 KB, JPG, Passport size, Light/White background",
    signatureRequirements: "[STANDARD] Signature: 10-40 KB, JPG, Blue/Black ink on white paper",
  },
  {
    title: "MPSC Rajyaseva Examination 2024",
    department: "Maharashtra Public Service Commission",
    category: "state-psc",
    states: ["Maharashtra"],
    ageMin: 19,
    ageMax: 38,
    ageRelaxation: "As per Maharashtra government norms",
    qualification: "Bachelor's Degree in any subject from a recognized University",
    applicationStartDate: addDays(today, -7),
    lastDate: addDays(today, 30),
    examDate: addDays(today, 95),
    applyUrl: "https://mpsc.gov.in",
    notificationPdfUrl: null,
    sourceName: "MPSC Official",
    sourceUrl: "https://mpsc.gov.in",
    isVerified: true,
    description: "MPSC Rajyaseva 2024 for Deputy Collector, Police Sub-Inspector, Section Officer and other Group A & B posts in Maharashtra Government.",
    salaryRange: "₹41,800 - ₹1,32,300 per month",
    vacancies: 800,
    photoRequirements: null,
    signatureRequirements: null,
  },
  {
    title: "NTA UGC NET December 2024",
    department: "National Testing Agency / UGC",
    category: "teaching",
    states: ["All India"],
    ageMin: 0,
    ageMax: 0,
    ageRelaxation: "No upper age limit for JRF (Junior Research Fellowship) - max 30 years. No limit for Lectureship/Assistant Professor.",
    qualification: "Master's Degree with 55% marks (50% for SC/ST/PwD). Final year students can apply conditionally.",
    applicationStartDate: addDays(today, -3),
    lastDate: addDays(today, 35),
    examDate: addDays(today, 75),
    applyUrl: "https://ugcnet.nta.ac.in",
    notificationPdfUrl: "https://ugcnet.nta.ac.in/Notifications/UGC_NET_Dec2024.pdf",
    sourceName: "NTA UGC NET",
    sourceUrl: "https://ugcnet.nta.ac.in",
    isVerified: true,
    description: "UGC NET December 2024 for determining eligibility for Assistant Professor and Junior Research Fellowship in Indian Universities and Colleges. 83 subjects.",
    salaryRange: "JRF: ₹37,000/month + HRA; Assistant Professor: ₹57,700+ per month",
    vacancies: null,
    photoRequirements: "[STANDARD] Photo: 10-200 KB, JPEG, White background, 3.5 x 4.5 cm",
    signatureRequirements: "[STANDARD] Signature: 4-30 KB, JPEG, Black or Blue ink on white paper",
  },
  {
    title: "Indian Navy Sailor MR Recruitment 2024 Batch",
    department: "Indian Navy",
    category: "defence",
    states: ["All India"],
    ageMin: 17,
    ageMax: 20,
    ageRelaxation: "SC/ST: No relaxation for Navy",
    qualification: "10th Pass from a recognized board",
    applicationStartDate: addDays(today, -20),
    lastDate: addDays(today, 7),
    examDate: addDays(today, 40),
    applyUrl: "https://www.joinindiannavy.gov.in",
    notificationPdfUrl: null,
    sourceName: "Indian Navy",
    sourceUrl: "https://joinindiannavy.gov.in",
    isVerified: true,
    description: "Indian Navy MR (Matric Recruit) batch 2024 recruitment for Cook and Steward. Short service commission.",
    salaryRange: "₹21,700 - ₹69,100 per month",
    vacancies: 400,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG, White background, Passport size",
    signatureRequirements: null,
  },
  {
    title: "SSC CHSL (10+2) Level Examination 2024",
    department: "Staff Selection Commission",
    category: "ssc",
    states: ["All India"],
    ageMin: 18,
    ageMax: 27,
    ageRelaxation: "OBC: 3 years, SC/ST: 5 years, Ex-servicemen: 3 years",
    qualification: "12th Pass from a recognized Board",
    applicationStartDate: addDays(today, -40),
    lastDate: addDays(today, 3),
    examDate: addDays(today, 55),
    applyUrl: "https://ssc.gov.in",
    notificationPdfUrl: "https://ssc.gov.in/SSCFileServer/PortalManagement/UploadedFiles/CHSL_2024.pdf",
    sourceName: "SSC Official",
    sourceUrl: "https://ssc.gov.in",
    isVerified: true,
    description: "SSC CHSL 2024 for Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), Postal Assistant (PA), Sorting Assistant (SA), Data Entry Operator (DEO).",
    salaryRange: "₹19,900 - ₹63,200 per month",
    vacancies: 3712,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG, White/Light background",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPEG",
  },
  {
    title: "IBPS Clerk XIV Recruitment 2024",
    department: "Institute of Banking Personnel Selection",
    category: "banking",
    states: ["All India"],
    ageMin: 20,
    ageMax: 28,
    ageRelaxation: "SC/ST: 5 years, OBC: 3 years, PwD: 10 years",
    qualification: "Graduate in any discipline from a recognised University",
    applicationStartDate: addDays(today, -15),
    lastDate: addDays(today, 14),
    examDate: addDays(today, 50),
    applyUrl: "https://ibps.in",
    notificationPdfUrl: null,
    sourceName: "IBPS Official",
    sourceUrl: "https://ibps.in",
    isVerified: true,
    description: "IBPS Clerk CRP XIV 2024 recruitment for Clerical Cadre in participating Public Sector Banks across India.",
    salaryRange: "₹19,900 - ₹47,920 per month",
    vacancies: 6128,
    photoRequirements: "[STANDARD] Photo: 20-50 KB, JPEG, White background",
    signatureRequirements: "[STANDARD] Signature: 10-20 KB, JPEG",
  },
];

async function seed() {
  console.log("Seeding jobs...");

  await db.delete(jobsTable);

  for (const job of jobs) {
    await db.insert(jobsTable).values(job);
  }

  console.log(`Seeded ${jobs.length} jobs successfully.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
