export const CATEGORIES = [
  { slug: "research-science",    name: "Research & Science",    color: "#7C3AED" },
  { slug: "medical",             name: "Medical",               color: "#EC4899" },
  { slug: "management-admin",    name: "Management & Admin",    color: "#0EA5E9" },
  { slug: "teaching",            name: "Teaching",              color: "#EAB308" },
  { slug: "judiciary",           name: "Judiciary",             color: "#6366F1" },
  { slug: "defence",             name: "Defence",               color: "#EF4444" },
  { slug: "technical-iti",       name: "Technical & ITI",       color: "#F97316" },
  { slug: "it-software",         name: "IT & Software",         color: "#06B6D4" },
  { slug: "finance-accounts",    name: "Finance & Accounts",    color: "#10B981" },
  { slug: "banking",             name: "Banking",               color: "#3B82F6" },
  { slug: "engineering",         name: "Engineering",           color: "#14B8A6" },
  { slug: "clerk-typist",        name: "Clerk & Typist",        color: "#8B5CF6" },
  { slug: "psu",                 name: "PSU",                   color: "#F59E0B" },
  { slug: "apprentice",          name: "Apprentice",            color: "#84CC16" },
  { slug: "ssc",                 name: "SSC",                   color: "#2563EB" },
  { slug: "police",              name: "Police",                color: "#DC2626" },
  { slug: "state-govt",          name: "State Govt",            color: "#059669" },
  { slug: "education-training",  name: "Education & Training",  color: "#D97706" },
  { slug: "healthcare-support",  name: "Healthcare Support",    color: "#DB2777" },
  { slug: "railways",            name: "Railway",               color: "#EA580C" },
  { slug: "agriculture-forestry",name: "Agriculture & Forestry",color: "#16A34A" },
  { slug: "law-security",        name: "Law & Security",        color: "#7C3AED" },
  { slug: "upsc",                name: "UPSC",                  color: "#9333EA" },
  { slug: "other",               name: "Other",                 color: "#6B7280" },
];

export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
  "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli",
  "Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep",
  "Puducherry", "All India",
];
